org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.244
loader_version_range=[1,)

mod_id=cpmvisualbridge
mod_name=CPM Visual Bridge
mod_license=All Rights Reserved
mod_version=0.1.0
mod_group_id=com.yofred.cpmvisualbridge

cpm_version=1.21v0.6.27a-neoforge
cybernetics_version=0.5.1
relics_curse_project=445274
relics_curse_file=8158315
pehkui_version=3.8.3+1.21-neoforge
