modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Yo_Fred"
description='''
Universal client-side bridge that keeps Customizable Player Models visible when other mods
replace player rendering or create player-shaped animations, copies, illusions and projections.
'''

[[mixins]]
config="${mod_id}-cybernetics.mixins.json"

[[mixins]]
config="${mod_id}-relics.mixins.json"

[[mixins]]
config="${mod_id}-mowzies.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="cpm"
type="required"
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="createcybernetics"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="relics"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="mowziesmobs"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="pehkui"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"
